[project]
name = "practical-ss26-team4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asrpy>=0.0.8",
    "autoreject>=0.4.3",
    "jupyterlab>=4.4.9",
    "matplotlib>=3.10.6",
    "mne>=1.10.1",
    "pandas>=2.2.2,<3",
    "seaborn>=0.13.2,<0.14",
    "pyriemann>=0.9",
    "pyxdf>=1.17.0",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.7.2",
    "scipy>=1.13.0",
    "umap-learn>=0.5.9.post2",
    "pyqt5>=5.15.11",
    "pyqt5-qt5<5.15.11",
    "torch",
    "pygame",
    "pylsl",
    "mne_icalabel"
]

[tool.uv.sources]
torch = { index = "pytorch-cuda" }

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
