import argparse
import subprocess
import sys
import time
from pathlib import Path


def main():

    parser = argparse.ArgumentParser(
        description="Mind the Lasers"
    )

    parser.add_argument(
        "--mode",
        choices=["live", "offline"],
        default="live",
        help="Pipeline mode.",
    )

    parser.add_argument(
        "--baseline",
        choices=["csp-lda", "sos-csp-lda", "zp-csp-lda", "bp-lda", "eegnet"],
        default="zp-csp-lda",
    )

    parser.add_argument(
        "--suffix",
        default="latest",
        help="Weight suffix generated by evaluate_pipelines, or latest.",
    )

    parser.add_argument(
        "--xdf",
        type=str,
        help="Offline XDF replay (required only for offline mode).",
    )

    parser.add_argument(
        "--ip",
        default="127.0.0.1",
    )

    parser.add_argument(
        "--port",
        default="5005",
    )

    parser.add_argument(
        "--input-scale",
        default="1e-6",
        help="Scale applied to live LSL EEG before inference.",
    )

    parser.add_argument(
        "--controller",
        choices=["pipeline", "keyboard", "both"],
        default="pipeline",
        help="Input source for the game.",
    )

    args = parser.parse_args()

    root = Path(__file__).resolve().parents[2]

    processes = []

    try:

        # ---------------------------------------------------------
        # Offline replay
        # ---------------------------------------------------------

        if args.mode == "offline":

            if args.xdf is None:
                parser.error("--xdf is required in offline mode.")

            streamer = subprocess.Popen(
                [
                    sys.executable,
                    "-m",
                    "mind_the_lasers.src.stream.streamer",
                    args.xdf,
                ]
            )

            processes.append(streamer)

            print("Started XDF streamer.")

            time.sleep(2)

        # ---------------------------------------------------------
        # Pipeline
        # ---------------------------------------------------------

        if args.controller in ("pipeline", "both"):

            pipeline = subprocess.Popen(
                [
                    sys.executable,
                    "-m",
                    "mind_the_lasers.src.pipeline.run_pipeline",
                    "--mode",
                    "live",
                    "--baseline",
                    args.baseline,
                    "--ip",
                    args.ip,
                    "--port",
                    args.port,
                    "--suffix",
                    args.suffix,
                    "--input-scale",
                    args.input_scale,
                ]
            )

            processes.append(pipeline)

            print("Started pipeline.")

            time.sleep(2)

        # ---------------------------------------------------------
        # Keyboard prediction sender
        # ---------------------------------------------------------

        if args.controller in ("keyboard", "both"):

            keyboard = subprocess.Popen(
                [
                    sys.executable,
                    "-m",
                    "mind_the_lasers.src.stream.key_press",
                    "--ip",
                    args.ip,
                    "--port",
                    args.port,
                ]
            )

            processes.append(keyboard)

            print("Started keyboard sender.")

            time.sleep(1)

        # ---------------------------------------------------------
        # Game
        # ---------------------------------------------------------

        game = subprocess.Popen(
            [
                sys.executable,
                "-m",
                "mind_the_lasers.src.game.run_game",
            ]
        )

        processes.append(game)

        print("Started game.")

        game.wait()

    except KeyboardInterrupt:

        print("\nStopping...")

    finally:

        for p in reversed(processes):

            if p.poll() is None:

                p.terminate()

        for p in reversed(processes):

            try:
                p.wait(timeout=2)

            except subprocess.TimeoutExpired:
                p.kill()


if __name__ == "__main__":
    main()
